--- Dockerfile	2022-04-04 11:02:54.113344490 +0400
+++ Dockerfile	2022-09-28 14:13:11.167271831 +0400
@@ -1,25 +1,25 @@
 FROM openjdk:11-jre
 
 ENV OPENFIRE_USER=openfire \
-    OPENFIRE_DIR=/usr/local/openfire \
-    OPENFIRE_DATA_DIR=/var/lib/openfire \
-    OPENFIRE_LOG_DIR=/var/log/openfire
+    OPENFIRE_DIR=/app \
+    OPENFIRE_DATA_DIR=/app/data \
+    OPENFIRE_LOG_DIR=/run/log
 
 RUN apt-get update -qq \
     && apt-get install -yqq sudo \
-    && adduser --disabled-password --quiet --system --home $OPENFIRE_DATA_DIR --gecos "Openfire XMPP server" --group $OPENFIRE_USER \
+    && adduser --disabled-password --system --home ${OPENFIRE_DATA_DIR} --gecos "Openfire XMPP server" --group ${OPENFIRE_USER} \
     && rm -rf /var/lib/apt/lists/*
 
 COPY ./build/docker/entrypoint.sh /sbin/entrypoint.sh
 RUN chmod 755 /sbin/entrypoint.sh
 
-COPY --chown=openfire:openfire ./distribution/target/distribution-base /usr/local/openfire
+COPY --chown=openfire:openfire ./distribution/target/distribution-base ${OPENFIRE_DIR}
 RUN mv ${OPENFIRE_DIR}/conf ${OPENFIRE_DIR}/conf_org \
     && mv ${OPENFIRE_DIR}/plugins ${OPENFIRE_DIR}/plugins_org \
     && mv ${OPENFIRE_DIR}/resources/security ${OPENFIRE_DIR}/resources/security_org
 
 LABEL maintainer="florian.kinder@fankserver.com"
-WORKDIR /usr/local/openfire
+WORKDIR ${OPENFIRE_DIR}
 
 EXPOSE 3478 3479 5005 5222 5223 5229 5262 5263 5275 5276 7070 7443 7777 9090 9091
 VOLUME ["${OPENFIRE_DATA_DIR}"]
