name: build-openfire
on: push

env:
  OPENFIRE_VERSION: v4.7.3

# Secrets requirements (set at 'Secrets' setting of Github repository)
#
# IMAGE_NAME
# REGISTRY
# REGISTRY_USERNAME
# REGISTRY_TOKEN

jobs:
  build:
    name: Build Openfire
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Openfire
        uses: actions/checkout@v3
        with:
          repository: igniterealtime/Openfire
          ref: ${{ env.OPENFIRE_VERSION }}

      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: patches

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          architecture: x64
          cache: maven
          distribution: adopt
          java-version: '11'

      - name: Patch files
        run: |
          patch -p0 < patches/JiveGlobals.java.patch

      - name: Run build
        run: |
          make build-openfire

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            ./build/docker/entrypoint.sh
            ./distribution/target/distribution-base
            ./Dockerfile
          key: distribution-base-${{ env.OPENFIRE_VERSION }}-${{ github.run_id }}

  build_and_push_docker_image:
    name: Build and Push Docker Image
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the build from cache
        uses: actions/cache@v3
        with:
          path: |
            ./build/docker/entrypoint.sh
            ./distribution/target/distribution-base
            ./Dockerfile
          key: distribution-base-${{ env.OPENFIRE_VERSION }}-${{ github.run_id }}

      - name: Patch files
        run: |
          patch -p0 < Dockerfile.patch
          patch -p0 < entrypoint.sh.patch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.IMAGE_NAME }}:${{ env.OPENFIRE_VERSION }}
            ${{ secrets.IMAGE_NAME }}:latest
